#!/bin/bash

pathfbz="/var/www/site1"
[ -d "$pathfbz" ] || { echo "ERR: directory $pathfbz/ doens't exist "; exit 1; }
cd $pathfbz

if [ -d "foobarbaz" ];	#if directory "foobarbaz" already exists, script will answer user to recreate it or do nothing
then
	while true; do
		read -p "Directory \"foobarbaz\" already exists in $pathfbz/, do you want to recreate it y/n? " yn
		case $yn in
	        	[Yy]* ) rm -R $pathfbz/foobarbaz; mkdir foobarbaz; break;;
	        	[Nn]* ) echo "Script execution cancelled by user "; exit 2;;
	        	* ) echo "Please answer yes or no.";;
	    	esac
	done
else
	mkdir foobarbaz
fi

[ -d foobarbaz ] || { echo "Directory \"foobarbaz\" creation was unsuccessful "; exit 3; }

cd foobarbaz

foo=0		#remainder of division by 3
bar=0		#remainder of division by 5
iDec=0		#decimal representation of a number with leading zeros
noteCount=0	#counter

for i in {0001..1000};	
do
	iDec=$((10#$i))
	foo=$(($iDec%3))	#if you try to use $i instead of $iDec, you'll catch an error at 0008, because 0008 is recognized by the system as unreal octal number
	bar=$(($iDec%5))
	
	if  (( $foo == 0 && $bar == 0 ));
	then
		echo "foobar" > $i.txt
		[ -f "$i.txt" ] || { echo "ERR: $i.txt doesn't exist "; exit 4; }	#file existance checking
		[ -s "$i.txt" ] || { echo "ERR: $i.txt is empty "; exit 5; }		#file emptiness checking
		let noteCount++	
	elif  (( $foo == 0 ));
	then
		echo "foo" > $i.txt
		[ -f "$i.txt" ] || { echo "ERR: $i.txt doesn't exist "; exit 6; }
		[ -s "$i.txt" ] || { echo "ERR: $i.txt is empty "; exit 7; }
		let noteCount++	
	elif  (( $bar == 0 ));
	then
		echo "bar" > $i.txt
		[ -f "$i.txt" ] || { echo "ERR: $i.txt doesn't exist "; exit 8; }
		[ -s "$i.txt" ] || { echo "ERR: $i.txt is empty "; exit 9; }
		let noteCount++	
	fi
done

fileCount=$( ls $pathfbz/foobarbaz | wc -l )	#file count equal to number of notes generated by wc -l

if [ "$noteCount" != "$fileCount" ];		#if file count is not equal to counter number script will return error, because of wrong files number
then
	echo "ERR: wrong files count, check $pathfbz/foobarbaz/error_log.txt for more information "
	echo "noteCount: $noteCount " >> error_log.txt
	echo "fileCount: $fileCount " >> error_log.txt
	exit 10
else
	echo "File creation was successful, $fileCount files created. "
fi

echo "Script createFoobarbaz DONE"	 
